[project]
name = "assistente-aluno"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepgram-sdk>= 7.1.0",
    "dotenv>=0.9.9",
    "fastapi>=0.136.1",
    "genanki>=0.13.1",
    "google-api-python-client>=2.196.0",
    "google-auth-httplib2>=0.4.0",
    "google-auth-oauthlib>=1.4.0",
    "groq>=1.2.0",
    "openai>=2.36.0",
    "playwright>=1.59.0",
    "pydantic-settings>=2.14.0",
    "qdrant-client>=1.17.1",
    "tqdm>=4.67.3",
    "transformers>=5.8.0",
    "uvicorn>=0.46.0",
    "streamlit>=1.57.0",
    "websockets>=16.0",
    "torch",
    "torchvision",
    "python-pptx>=1.0.2",
    "easyocr>=1.7.2",
    "boto3>=1.43.6",
    "onnxruntime-gpu>=1.25.1",
    "langsmith>=0.8.3",
    "fastembed>=0.8.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = [".", "scripts"]
